[package]
name = "framebuffer-vesa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
framebuffer = { path = "../framebuffer" }
spin = "0.9.8"
bootloader_api = "0.11.5"