[package]
name = "distros-framebuffer-vesa"
version = "0.1.0"
edition = "2021"

[dependencies]
distros-framebuffer = { path = "../framebuffer" }

spin.workspace = true

bootloader_api.workspace = true