[package]
name = "distros"
version = "0.1.0"
authors = ["Aleksei Arsenev <alesharikReserv@yandex.ru>"]
edition = "2018"

[dependencies]
bootloader = { version = "0.9.18", features = ["map_physical_memory"] }
spin = "0.9.0"
vga = { git = "https://github.com/rust-osdev/vga.git" }
volatile = "0.4.4"
x86_64 = "0.14.3"
linked_list_allocator = "0.9.0"
acpi = "2.3.1"
x2apic = { git = "https://github.com/alesharik/x2apic-rs.git", branch = "xapic"}
raw-cpuid = "9.0.0"
bitflags = "1.2.1"
chrono = { version = "0.4", default-features = false, features = ["alloc"] }
fixedbitset = { version = "0.4.0", default-features = false }
rand = { version = "0.8.3", default-features = false, features = ["alloc"] }
rand_pcg = "0.3.0"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]

[build-dependencies]
cc = "1.0.68"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"