[package]
name = "distros-interrupt"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static.workspace = true

bitflags.workspace = true
fixedbitset.workspace = true

x86_64.workspace = true

spin.workspace = true

log.workspace = true
