[package]
name = "distros-memory"
version = "0.1.0"
edition = "2021"

[dependencies]
talc.workspace = true

x86_64.workspace = true
bootloader_api.workspace = true

arrayvec.workspace = true

spin.workspace = true

log.workspace = true
